name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4
  
      # 2. Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      # 3. Build de l’image Docker backend
      - name: Build Docker image backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mini-blog:backend-latest ./backend
  
      # 4. Push de l’image backend sur Docker Hub
      - name: Push Docker image backend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mini-blog:backend-latest
      
      # 5. Build de l'image Docker db
      - name: Build Docker image db
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mini-blog:db-latest ./frontend

      # 6. Push de l'image db sur Docker Hub
      - name: Push Docker image db
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mini-blog:db-latest

      # 7. Build de l'image Docker frontend
      - name: Build Docker image frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mini-blog:frontend-latest ./frontend

      # 8. Push de l'image frontend sur Docker Hub
      - name: Push Docker image frontend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mini-blog:frontend-latest 
